'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),N=require('../web/netcode.js');
function theme(){const w={};vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../web/theme.js'),'utf8'),{window:w,document:{documentElement:{dataset:{},style:{}},querySelector:()=>null}});return w.leqraTheme;}
const canon=['#d2f65a','#ff9679','#73cee4','#c5a2ff','#ffc46b','#ff83bd','#75f0cb','#b7c6ee'];
test('eight distinct named dark palettes use neon-blue interface accent',()=>{const t=theme();assert.equal(t.colors.length,8);assert.equal(t.colorNames.length,8);assert.equal(new Set(t.colors).size,8);assert.equal(t.palette.accent,'#00c8ff');assert.equal(t.resolved,'dark');});
test('canonical color identity maps once into the dark palette',()=>{const t=theme();for(let i=0;i<8;i++){assert.equal(t.assetColor(canon[i]),t.colors[i]);assert.equal(t.assetColor(t.assetColor(canon[i])),t.colors[i]);}});
test('every power-up has a dark palette paint',()=>{const t=theme();for(const kind of ['rapid','scatter','shield','homing','grenade','speed','laser','scope','cannon','ghost'])assert.match(t.powerColor(kind),/^#[0-9a-f]{6}$/i,kind);});
test('paint mapping preserves alpha and ignores unknown non-color objects',()=>{const t=theme();for(const c of canon)assert.equal(t.assetColor(c+'77'),t.assetColor(c)+'77');const v={};assert.equal(t.assetColor(v),v);});
test('compact machine-gun records expand with exact radius, volley, color and state',()=>{const a=[81,7,14,3,88.2,92.5,-846,0,.5,1,2,5];const b=N.expandMachineBullets([a],canon)[0];assert.equal(b.id,81);assert.equal(b.owner,7);assert.equal(b.shotSerial,14);assert.equal(b.spawnSerial,3);assert.equal(b.r,3.5/3);assert.equal(b.kind,'rapid');assert.equal(b.color,canon[5]);assert.equal(b.vx,-846);assert.equal(b.life,1);assert.equal(b.target,-1);});
test('compact decoder bounds records and rejects malformed or nonfinite values',()=>{assert.deepEqual(N.expandMachineBullets(null,canon),[]);for(const a of [[],[1,0,1,1,0,0,846,0,0,1,0,8],[1,9,1,1,0,0,846,0,0,1,0,0],[1,0,1,1,NaN,0,846,0,0,1,0,0]])assert.equal(N.expandMachineBullets([a],canon).length,0);const ok=[1,0,1,1,0,0,846,0,0,1,0,0];assert.equal(N.expandMachineBullets(Array(1700).fill(ok),canon).length,768);});
test('both local machine guns predict independently and allow later confirmed streaming',()=>{const s=new N.ShotPresentation();const opts={active:true,free:96,need:1,cooldown:0,ttl:600};const tanks=[0,7].map(id=>({id,alive:true,spawnSerial:1,shotSerial:0,cooldown:0,power:'rapid',machineRounds:300}));for(const t of tanks)s.sync(t,'playing',0);for(let step=0;step<60;step++){for(const t of tanks){const now=step*N.STEP_MS+.01;const v=s.tryFire(t,true,now,opts);assert.ok(v);v.shells=[{}];assert.equal(s.tryFire(t,true,now+1,opts),null);t.shotSerial=v.shot;s.sync(t,'playing',now+2);}}for(const t of tanks)assert.equal(t.shotSerial,60);});
